 Company.create(company_name: "株式会社あああ",company_work_time: 7,company_break_time: 1,company_closing_date: 5)
 User.create(name: "しゃちょー",email: "6@gmail.com",password:"666666",company_id: 1 ,admin: true)
 User.create(name: "山田太郎",email: "1@gmail.com",password:"111111",company_id: 1,admin: false)
User.create(name: "田中正義",email: "2@gmail.com",password:"222222",company_id: 1,admin: false)
User.create(name: "近藤純",email: "3@gmail.com",password:"333333",company_id: 1,admin: false)
User.create(name: "前田敏史",email: "4@gmail.com",password:"444444",company_id: 1,admin: false)
User.create(name: "辻公平",email: "5@gmail.com",password:"555555",company_id: 1,admin: false)
User.create(name: "岡田悠馬",email: "7@gmail.com",password:"777777",company_id: 1,admin: false)
User.create(name: "高橋良輔",email: "8@gmail.com",password:"888888",company_id: 1,admin: false)
User.create(name: "田中信雄",email: "9@gmail.com",password:"999999",company_id: 1,admin: false)
User.create(name: "加藤茂雄",email: "a@gmail.com",password:"aaaaaa",company_id: 1,admin: false)
 #UserWork.create(work_element:"aaa",user_id: 1)

 Client.create(client_name: "クライアントA",client_addr: "愛知県春日井市３丁目 高森台",client_bill: "愛知県春日井市３丁目 高森台",client_phone_number: 3131,client_fax: 3133 ,company_id: 1)
 Client.create(client_name: "クライアントB",client_addr: "愛知県春日井市３丁目 高森台",client_bill: "愛知県春日井市３丁目 高森台",client_phone_number: 3131,client_fax: 3133 ,company_id: 1)
 Client.create(client_name: "クライアントC",client_addr: "岐阜県大垣市上屋",client_bill: "岐阜県大垣市上屋",client_phone_number: 1323,client_fax: 523 ,company_id: 1)
 Client.create(client_name: "クライアントD",client_addr: "愛知県名古屋市東区徳川１丁目",client_bill: "愛知県名古屋市東区徳川１丁目",client_phone_number: 244,client_fax: 425 ,company_id: 1)
 Client.create(client_name: "クライアントE",client_addr: "愛知県名古屋市千種区",client_bill: "愛知県名古屋市千種区",client_phone_number: 4243,client_fax: 4242 ,company_id: 1)
 Client.create(client_name: "クライアントF",client_addr: "愛知県名古屋市千種区若水２丁目7−４ 市営仲田荘",client_bill: "愛知県名古屋市千種区若水２丁目7−４ 市営仲田荘",client_phone_number: 17,client_fax: 29 ,company_id: 1)

ClientWork.create(work_place: "現場１",work_name: "解体作業",salary_per_man: "15000",client_id: 1)
ClientWork.create(work_place: "現場2",work_name: "鉄骨組み立て",salary_per_man: "20000",client_id: 2)
ClientWork.create(work_place: "現場3",work_name: "歩道案内",salary_per_man: "18000",client_id: 2)
ClientWork.create(work_place: "現場4",work_name: "監査",salary_per_man: "20000",client_id: 3)
ClientWork.create(work_place: "現場5",work_name: "溶接",salary_per_man: "13000",client_id: 3)
ClientWork.create(work_place: "現場6",work_name: "撤去兼後片付け",salary_per_man: "15000",client_id: 3)
ClientWork.create(work_place: "現場7",work_name: "設計",salary_per_man: "17000",client_id: 4)
ClientWork.create(work_place: "現場8",work_name: "改装工事",salary_per_man: "18000",client_id: 4)
